### ISSUE TITLE
Not working on census or mapquest, but example data works on Census batch API

### ISSUE THREAD

**Issue by spara** [tmcw-up-for-adoption/geocodify#7]
Here's the test data:

"name","street_address","city","state","zipcode"
"1800-JC Project inc.","1199 E. Bayshore St.","East Palo Alto","CA","94303"
"1st Free Methodist Church","3430 Michael Drive","Redwood City","CA","94063"
"1st Tongan United Methodist Church PM","560 El Camino Real","San Bruno","CA","94066"
"3rd Street Community Center","160 N. Third Street","San Jose","CA","95112"
"AC Macklin Wholeness Center-1st Step Com. Services","2170 Capitol Ave.","East Palo Alto","CA","94303"

The Census API batch request works:

 curl --form addressFile=@census_test.csv --form benchmark=9 http://geocoding.geo.census.gov/geocoder/locations/addressbatch --output geocoderesult.csv

geocodify throws this error using census:

~/Code for America/code/shfb » geocodify census_test.csv --addressfields [ street_address city state zipcode]  --source=census   

/usr/local/lib/node_modules/geocodify/index.js:62
                        lat: data.result.addressMatches[0].coordinates.y,
                                                          ^
TypeError: Cannot read property 'coordinates' of undefined
    at /usr/local/lib/node_modules/geocodify/index.js:62:59
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/geocodify/node_modules/concat-stream/index.js:32:43)
    at ConcatStream.EventEmitter.emit (events.js:117:20)
    at finishMaybe (/usr/local/lib/node_modules/geocodify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:14)
    at afterWrite (/usr/local/lib/node_modules/geocodify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:335:3)
    at /usr/local/lib/node_modules/geocodify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:322:9
    at process._tickCallback (node.js:415:13)

mapquest throws this error:

~/Code for America/code/shfb » geocodify census_test.csv --addressfields [ street_address city state zipcode]  --source=mapquestopen   

TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:150:14)
    at PassThrough.Writable.write (_stream_writable.js:179:12)
    at write (/usr/local/lib/node_modules/geocodify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:605:24)
    at flow (/usr/local/lib/node_modules/geocodify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:614:7)
    at Transform.pipeOnReadable (/usr/local/lib/node_modules/geocodify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:646:5)
    at Transform.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (/usr/local/lib/node_modules/geocodify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:430:10)
    at emitReadable (/usr/local/lib/node_modules/geocodify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:426:5)
    at readableAddChunk (/usr/local/lib/node_modules/geocodify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at Transform.Readable.push (/usr/local/lib/node_modules/geocodify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)

**Comment by tmcw** [comment]
My bad, csv output was broken. Fixed in c957645ff003ebea92e6135ed0b0827b06a11c85
